all:
	g++ -O2 -s -Wall -Wextra -c Point.cpp
	g++ -O2 -s -Wall -Wextra -c Vector.cpp
	g++ -O2 -s -Wall -Wextra -c Hermite.cpp
	g++ -O2 -s -Wall -Wextra -c Bezier.cpp
	g++ -O2 -s -Wall -Wextra -c SurfaceParam.cpp
	g++ -O2 -s -Wall -Wextra -c TP_OPENGL.cpp
	g++ *.o -o tp -lGL -lglut
