all:
	g++ -s -Wall -Wextra -c Point.cpp
	g++ -s -Wall -Wextra -c Vector.cpp
	g++ -s -Wall -Wextra -c Hermite.cpp
	g++ -s -Wall -Wextra -c Bezier.cpp
	g++ -s -Wall -Wextra -c SurfaceParam.cpp
	g++ -s -Wall -Wextra -c Sphere.cpp
	g++ -s -Wall -Wextra -c Box.cpp
	g++ -s -Wall -Wextra -c FromFile.cpp
	g++ -s -Wall -Wextra -c TP_OPENGL.cpp
	g++ *.o -o tp -lGL -lglut
